-- province.sql
-- 34 tỉnh/thành phố trực thuộc trung ương
INSERT INTO province (id, name) VALUES
(1,  'Hà Nội'),
(4,  'Cao Bằng'),
(8,  'Tuyên Quang'),
(11, 'Điện Biên'),
(12, 'Lai Châu'),
(14, 'Sơn La'),
(15, 'Lào Cai'),
(19, 'Thái Nguyên'),
(20, 'Lạng Sơn'),
(22, 'Quảng Ninh'),
(24, 'Bắc Ninh'),
(25, 'Phú Thọ'),
(31, 'Hải Phòng'),
(33, 'Hưng Yên'),
(37, 'Ninh Bình'),
(38, 'Thanh Hóa'),
(40, 'Nghệ An'),
(42, 'Hà Tĩnh'),
(44, 'Quảng Trị'),
(46, 'Huế'),
(48, 'Đà Nẵng'),
(51, 'Quảng Ngãi'),
(52, 'Gia Lai'),
(56, 'Khánh Hòa'),
(66, 'Đắk Lắk'),
(68, 'Lâm Đồng'),
(75, 'Đồng Nai'),
(79, 'Hồ Chí Minh'),
(80, 'Tây Ninh'),
(82, 'Đồng Tháp'),
(86, 'Vĩnh Long'),
(91, 'An Giang'),
(92, 'Cần Thơ'),
(96, 'Cà Mau');