spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
#server:
#  port: 8443                  # dùng 8443 để test local trước, sau này production đổi thành 443
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: 123456
#    key-store-type: PKCS12
#    key-alias: tomcat










#keytool -genkeypair -alias tomcat -keyalg RSA -keysize 2048 -keystore keystore.p12 -storetype PKCS12 -validity 3650 -dname "CN=localhost" -storepass 123456 -keypass 123456