server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # ======================================
        #                PRODUCT SERVICE
        # ======================================

        # 1. PRODUCT
        - id: product
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=0

        # 2. CATEGORY
        - id: category
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/categories/**
          filters:
            - StripPrefix=0

        # 3. DISCOUNT
        - id: discount
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/discounts/**
          filters:
            - StripPrefix=0
        # 4. variants
        - id: product-variant
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/variants/**
          filters:
            - StripPrefix=0
        # ======================================
        #                AUTH SERVICE
        # ======================================

        # PUBLIC ENDPOINTS: login, signup, validate, etc.
        - id: auth-public
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=0

        # USER ENDPOINTS: profile, update, get info
        - id: auth-user
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0

        - id: auth-user
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/admin/**
          filters:
            - StripPrefix=0

        # ADDRESS ENDPOINTS: CRUD address
        - id: auth-address
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/address/**
          filters:
            - StripPrefix=0

        # ADDRESS ENDPOINTS: CRUD address
        - id: auth-address-shipping
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/shipping/**
          filters:
            - StripPrefix=0

        # ======================================
        #                Cart SERVICE
        # ======================================

        # 5. CART SERVICE
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/carts/**
          filters:
            - StripPrefix=0

        # ======================================
        #                Order SERVICE
        # ======================================
        # ORDER SERVICE
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**

        # ======================================
        #                Payment SERVICE
        # ======================================
        # PAYMENT SERVICE
        - id: payment-service
          uri: lb://PAYMENT
          predicates:
            - Path=/api/payments/**

        # ======================================
        #                IMAGE SEARCH SERVICE
        # ======================================

        # IMAGE SEARCH (Python service)
        - id: image-search-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/image/**

        # ======================================
        #                EUREKA
        # ======================================
        # EUREKA UI
        - id: eureka-ui
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=0

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowed-methods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
            allowed-headers: [ "*" ]
            exposed-headers: [ "*" ]
            allow-credentials: true